Resources:
  TransfersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: '${self:provider.stage}-transfers'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'created'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
        - AttributeName: 'created'
          KeyType: 'RANGE'
      BillingMode: 'PAY_PER_REQUEST'
