Resources:
  AccountsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: '${self:provider.stage}-accounts'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      BillingMode: 'PAY_PER_REQUEST'
