openapi: '3.0.0'
info:
  description: 'Example simple payments service'
  version: 1.0.0
  title: Example simple payments service
tags:
  - name: Account
    description: Account specific functionality
paths:
  /account/{accountId}:
    get:
      tags:
        - Account
      summary: Get an account record
      description: Gets an account record by account id
      parameters:
        - name: accountId
          in: path
          required: true
          description: Account ID
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '403':
          description: Unauthorized
        '404':
          description: Not Found
  /account/{accountId}/transfers:
    get:
      tags:
        - Account
      summary: List transfer records in date order
      description: 'List transfer records in date order'
      parameters:
        - name: accountId
          in: path
          required: true
          description: Account ID
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferListResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '403':
          description: Unauthorized
        '404':
          description: Not Found
    post:
      tags:
        - Account
      summary: Create a transfer record
      description: Transfer money between accounts
      parameters:
        - name: accountId
          in: path
          required: true
          description: Account ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransferRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    Account:
      properties:
        id:
          type: string
        balance:
          type: number
    AccountResponse:
      $ref: '#/components/schemas/Account'
    CreateTransferRequest:
      required:
        - to
        - type
        - amount
      properties:
        to:
          type: string
        type:
          type: string
        amount:
          type: number
    Transfer:
      properties:
        id:
          type: string
        to:
          type: string
        action:
          type: string
          enum:
            - DEBIT
            - CREDIT
        amount:
          type: number
    TransferListResponse:
      properties:
        total:
          type: number
          format: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/Transfer'
