openapi: '3.0.0'
info:
  description: 'Example spending tracker service'
  version: 1.0.0
  title: Example spending tracker service
tags:
  - name: Account
    description: Account specific functionality
  - name: Transfer
    description: Transfer specific functionality
paths:
  /accounts:
    post:
      tags:
        - Account
      summary: Create an account record
      description: Creates an account to store funds
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /accounts/{accountId}:
    get:
      tags:
        - Account
      summary: Get an account record
      description: Gets an account record by account id
      parameters:
        - name: accountId
          in: path
          required: true
          description: Account ID
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '403':
          description: Unauthorized
        '404':
          description: Not Found
  /accounts/{accountId}/transfers:
    get:
      tags:
        - Transfer
      summary: List transfer records in date order
      description: 'List transfer records in date order'
      parameters:
        - name: accountId
          in: path
          required: true
          description: Account ID
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferListResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '403':
          description: Unauthorized
        '404':
          description: Not Found
  /accounts/{accountId}/transfers/credit:
    post:
      tags:
        - Transfer
      summary: Create a credit transfer record
      description: Credit an account
      parameters:
        - name: accountId
          in: path
          required: true
          description: Account ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /accounts/{accountId}/transfers/debit:
    post:
      tags:
        - Transfer
      summary: Create a debit transfer record
      description: Debit an account
      parameters:
        - name: accountId
          in: path
          required: true
          description: Account ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    AccountResponse:
      properties:
        id:
          type: string
        balance:
          type: number
    TransferRequest:
      required:
        - value
      properties:
        transactionId:
          type: string
        value:
          type: number
    Transfer:
      properties:
        type:
          type: string
          enum:
            - DEBIT
            - CREDIT
        id:
          type: string
        accountId:
          type: string
        value:
          type: number
        created:
          type: string
    TransferListResponse:
      type: array
      items:
        $ref: '#/components/schemas/Transfer'
